// Generated by CoffeeScript 1.6.3
(function() {
  var Firebase, fb, unique_identifier;

  Firebase = require('./firebase');

  unique_identifier = "h3kf394";

  fb = new Firebase("https://throw-it-up.firebaseio.com" + unique_identifier);

}).call(this);
